#
# Find which apps or libs are Affected from this push
#
# Created April 9th, 2022
# @author: ywarezk
# @version: 0.2.0
# @license: MIT
#

name: "Custom deploy for az"
description: Deploy the az

runs:
  using: composite

  steps:
    - name: test hello
      id: affected
      shell: bash
      run: |
        echo "hello deploy az"
