#
# Prepares a node environment with the source code
#
# Created April 14th, 2022
# @author: ywarezk
# @version: 0.2.0
# @license: MIT
#

name: Setup
description: Sets up a node environment

inputs:
  workload_identity_provider:
    description: For authentication
    required: true
  service_account:
    description: Github actions service account
    required: true
  project:
    description: The project to identity gcloud to
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate OIDC
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.2
        cache: npm
    - run: |
        npm run artifactregistry-login
        npm ci
      shell: bash

    - name: 'Setup gcloud api'
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        project_id: '${{ inputs.project }}'
