project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
skip_untranslated_strings: 1
commit_message: '[ci skip]'
preserve_hierarchy: 1
files:
  - source: /messages/en.json
    translation: /messages/%two_letters_code%.json
  - source: /content/en/**/*
    translation: /content/%two_letters_code%/**/%original_file_name%
