#
# Find which apps or libs are effected from this push
#
# Created April 9th, 2022
# @author: ywarezk
# @version: 0.2.0
# @license: MIT
#

name: "Effected apps/libs"
description: Find what are the apps and libs that are changed from the last successful build

runs:
  using: composite
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      id: setSHAs
      uses: nrwl/nx-set-shas@v2

    - name: Find effected apps and libs
      shell: bash
      run: |
        npx nx affected:apps --base=${{ steps.setSHAs.outputs.base }} --head=${{ steps.setSHAs.outputs.head }} --plain
        npx nx affected:libs --base=${{ steps.setSHAs.outputs.base }} --head=${{ steps.setSHAs.outputs.head }} --plain
