#
# will run the following:
#   - lint
#   - unit test
#   - build
#   - e2e test
#   - deploy
#
# Created April 9th, 2022
# @author: ywarezk
# @version: 0.1.0
# @license: MIT
#
#

name: CI

on:
  push:
    branches:
      - "main"
  create:
    tags:
      - v*

permissions: write-all
jobs:

  # Find what affected apps we need to build
  affected:
    runs-on: ubuntu-latest
    outputs:
      affectedApps: ${{ steps.affectedAppsLibs.outputs.apps }}
      affectedLibs: ${{ steps.affectedAppsLibs.outputs.libs }}
      affectedAll: ${{ steps.affectedAppsLibs.outputs.all }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Authenticate OIDC
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.WI_PROVIDER }}
          service_account: ${{ secrets.SA_GA }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: npm
      - run: |
          npm run artifactregistry-login
          npm ci

      - name: Affected apps/libs
        uses: ./.github/actions/affected
        id: affectedAppsLibs

  lint:
    needs: affected
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        appsLibs: ${{ fromJson(needs.affected.outputs.affectedAll) }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: npm
      - run: |
          npm run artifactregistry-login
          npm ci

      - uses: ./.github/actions/lint
        with:
          app: ${{ matrix.appsLibs }}



