#
# will run the following:
#   - lint
#   - unit test
#   - build
#   - e2e test
#   - deploy
#
# Created April 9th, 2022
# @author: ywarezk
# @version: 0.1.0
# @license: MIT
#
#

name: CI

on:
  push:
    branches:
      - "main"
  create:
    tags:
      - v*

jobs:

  # Find what effected apps we need to build
  effected:
    runs-on: ubuntu-latest
    steps:
      - name: Effected apps/libs
        uses: ./.github/actions/effected.yaml



