# 
# This will trigger the E2E workflow.
# IMPORTANT: this is always taken from main - so if this is changed in branch it won't be applied
# until this is merged to main
# This behaviour is because the repository_dispatch trigger
#
# Created August 16th, 2025
# @author ywarezk
# @license MIT
# 

name: Trigger E2E
  
on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'  
jobs:
  run-e2es:    
    runs-on: ubuntu-latest
    steps:                
      - uses: actions/create-github-app-token@v2.1.1
        id: app-token
        with:
          app-id: ${{ vars.ACADEMEEZ_APP_ID }}
          private-key: ${{ secrets.ACADEMEEZ_APP_PRIVATE_KEY }}
          
      - name: Trigger workflow with SHA
        uses: actions/github-script@v7
        if: ${{ github.event.client_payload.environment != 'production' }}
        with:
          script: |
            const sha = `${{ github.event.client_payload.git.sha }}`
            // Find branches that contain this commit
            const { data: branches } = await github.rest.repos.listBranchesForHeadCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha,
            })
            if (!branches.length) {
              core.setFailed(`No branch contains commit ${sha}`)
              return
            }
            // Choose the first branch (or add your own selection logic)
            const ref = branches[0].name
          
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'e2e.yml', // Replace with your workflow file name
              ref,
              inputs: {
                ref: sha,
                url: `${{ github.event.client_payload.url }}`
              }
            });
          
      