# 
# Vercel bot will build a preview environment for each pull request.
# This workflow will run E2E tests against that preview environment.
# E2E run is connected to sha
#
# Created August 16th, 2025
# @author: ywarezk
# @license: MIT
# 

name: E2E Tests
 
on:  
  workflow_dispatch:
    inputs:
      ref:
        description: "Commit SHA or branch to test"
        required: true
      url:
        description: "Preview environment URL"
        required: true
        
jobs:
  run-e2es:    
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/create-github-app-token@v2.1.1
        id: app-token
        with:
          app-id: ${{ vars.ACADEMEEZ_APP_ID }}
          private-key: ${{ secrets.ACADEMEEZ_APP_PRIVATE_KEY }}
          
      - name: E2E check
        uses: actions/github-script@v7.0.1
        id: e2e-check
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const response = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: `E2E`,
              head_sha: '${{ inputs.ref }}',
              status: 'in_progress',
              started_at: new Date().toISOString(),
            });
            console.log('response is:', response.data);
            return response.data.id;
      
      - name: Checkout code
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 1
          
      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version-file: '.nvmrc'   # automatically reads Node version from .nvmrc
          cache: 'npm'                  # enables npm cache based on lock file

      - name: Install dependencies
        run: npm ci
          
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
    
      - name: run tests
        env:
          BASE_URL: ${{ inputs.url }} # 👈 preview env URL
        run: |
          npx playwright test
          
      # Upload *all* artifacts (videos, screenshots, traces, html report)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-test-results
          path: |
            test-results/
          retention-days: 7
          if-no-files-found: warn
          
      - name: Upload playwright report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: playwright-report
          path: |
            playwright-report/
          retention-days: 7
          if-no-files-found: warn
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          override_branch: main
      
      - name: Set e2e check to success
        if: ${{ success() }}
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: ${{ steps.e2e-check.outputs.result }},
              conclusion: 'success',
              status: 'completed',
            });
      
      - name: Update deploy check on fail
        if: (failure() || cancelled()) && steps.e2e-check.outputs.result != ''
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |            
            github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: ${{ steps.e2e-check.outputs.result }},
              conclusion: 'failure',
              status: 'completed',
            });