#
# Find which apps or libs are effected from this push
#
# Created April 9th, 2022
# @author: ywarezk
# @version: 0.2.0
# @license: MIT
#

name: "Effected apps/libs"

# called workflow
on:
  workflow_dispatch:

jobs:
  effected:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: npm
      - run: npm ci
      - run: "npx nx lint ${{ github.event.inputs.app }} "
